# Generated by Django 2.1.8 on 2019-05-07 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friendlylink',
            old_name='title',
            new_name='name',
        ),
    ]
