# Generated by Django 2.1.8 on 2019-06-03 09:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostNumbers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('num_times', models.IntegerField(blank=True, default=5, null=True, verbose_name='发帖次数')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='activity_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='ip地址'),
        ),
        migrations.AlterField(
            model_name='user',
            name='biography',
            field=models.TextField(blank=True, null=True, verbose_name='个人简介'),
        ),
        migrations.AlterField(
            model_name='user',
            name='company',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='所在公司'),
        ),
        migrations.AlterField(
            model_name='user',
            name='github',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='github'),
        ),
        migrations.AlterField(
            model_name='user',
            name='instagram',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='instagram'),
        ),
        migrations.AlterField(
            model_name='user',
            name='linkedin',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='linkedin'),
        ),
        migrations.AlterField(
            model_name='user',
            name='location',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='所在地'),
        ),
        migrations.AlterField(
            model_name='user',
            name='telegram',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='telegram'),
        ),
        migrations.AlterField(
            model_name='user',
            name='twitter',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='twitter'),
        ),
        migrations.AlterField(
            model_name='user',
            name='website',
            field=models.URLField(blank=True, max_length=100, null=True, verbose_name='个人网站'),
        ),
        migrations.AlterField(
            model_name='user',
            name='weibo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='微博'),
        ),
        migrations.AddField(
            model_name='postnumbers',
            name='master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_post_times', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
    ]
