# Generated by Django 2.1.8 on 2019-05-22 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190518_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_online',
            field=models.IntegerField(default=0, verbose_name='是否在线'),
        ),
    ]
