# Generated by Django 2.1.8 on 2019-05-23 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_last_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='activity_ip',
            field=models.GenericIPAddressField(null=True, verbose_name='ip地址'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_activity',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='最后访问时间'),
        ),
    ]
