# Generated by Django 2.1.8 on 2019-05-27 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='icon',
            field=models.ImageField(null=True, upload_to='icon/board'),
        ),
    ]
