# Generated by Django 2.1 on 2018-11-22 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_auto_20181119_2157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='tags',
        ),
    ]
