# Generated by Django 2.1.8 on 2019-05-28 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_board_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='is_top',
            field=models.IntegerField(default=0),
        ),
    ]
