# Generated by Django 2.1.8 on 2019-05-08 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_auto_20190508_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='comment_num',
            field=models.IntegerField(default=0),
        ),
    ]
