# Generated by Django 2.1.8 on 2019-06-05 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_auto_20190604_1643'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'verbose_name': '回复', 'verbose_name_plural': '回复'},
        ),
        migrations.AlterField(
            model_name='board',
            name='description',
            field=models.CharField(max_length=100, verbose_name='简介'),
        ),
        migrations.AlterField(
            model_name='board',
            name='icon',
            field=models.ImageField(null=True, upload_to='icon/board', verbose_name='图标'),
        ),
        migrations.AlterField(
            model_name='board',
            name='is_top',
            field=models.BooleanField(default=False, verbose_name='是否出现在导航栏'),
        ),
        migrations.AlterField(
            model_name='board',
            name='name',
            field=models.CharField(max_length=30, unique=True, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='board',
            name='path',
            field=models.CharField(max_length=100, verbose_name='路径'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='ban_comments',
            field=models.BooleanField(default=True, verbose_name='是否允许回复'),
        ),
    ]
