# Generated by Django 2.1.8 on 2019-06-05 03:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum', '0006_auto_20190605_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='replay_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replay_user', to=settings.AUTH_USER_MODEL, verbose_name='回复对象'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_user', to=settings.AUTH_USER_MODEL, verbose_name='回复者'),
        ),
    ]
