# Generated by Django 2.1.8 on 2019-06-10 03:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum', '0007_auto_20190605_1134'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageTips',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tips_action', models.CharField(max_length=20, verbose_name='操作')),
                ('tips_content', models.TextField(verbose_name='提醒内容')),
                ('create_at', models.DateTimeField(verbose_name='结束时间')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tips_receiver', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tips_sender', to=settings.AUTH_USER_MODEL)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.Topic')),
            ],
        ),
    ]
