# Generated by Django 2.1.8 on 2019-06-10 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0008_messagetips'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagetips',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='时间'),
        ),
    ]
